- id: '1683608811710'
  alias: Andy - Open Garage when Arriving Home
  description: Open Garage when Arriving Home
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icloud3_v3_zone_distance")  | float
      <= 0.20}}'
  - platform: state
    entity_id:
    - sensor.andys_iphone_icloud3_v3_zone_name
    to: Home
  condition:
  - condition: state
    entity_id: input_boolean.andy_driving_flag
    state: 'on'
  - condition: not
    conditions:
    - condition: time
      after: '23:00:00'
      before: 06:00:00
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    alias: Make sure it is not between 11pm - 6am
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_andysiphone15_app
    data:
      title: Love you boo.
      message: Come in my Homie. Hope today was well. Let's chill.
  mode: single
- id: '1689609244173'
  alias: Washer Machine - Wash cycle finish
  description: Washer Machine - Wash cycle finish
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.eve_energy_7a9c_power
      starting_hysteresis: 1
      starting_threshold: 5
      finishing_threshold: 15
      actions:
      - service: notify.mobile_app_andys_iphone_15
        data:
          message: Washer has finished. Get it before it stinks, ew!
          title: Washer Machine Cycle Finished
        alias: 'Notify Andy: Wash COMPLETED'
      - service: notify.mobile_app_shannonsiphone14_iosapp
        data:
          message: The washing cycle has just finished. Those clothes are sparkling
            clean but still a bit shy and wet. It’s the perfect time to give them
            a warm hug in the dryer or let them dance in the fresh air on a clothesline.
            Whatever you choose, I'm here to remind you and make life a little easier.
            Let’s turn this chore into a cheer!
          title: Wash Cycle has COMPLETED!
        alias: 'Notify Shannon: Wash COMPLETED'
      pre_actions:
      - service: notify.mobile_app_andys_iphone_15
        data:
          title: Washer machine cycle just started
          message: I'll let you know when it's done, sir.
        alias: 'Notify Andy: Wash STARTED'
      - service: notify.mobile_app_shannonsiphone14_iosapp
        data:
          message: Just wanted to let you know that the washing machine has begun
            its magical journey of cleaning. While I take care of the spin cycles,
            why not steal some moments together? A good time for a cozy chat or a
            sweet cup of coffee, perhaps.
          title: Wash Cycle has STARTED!
        alias: 'Notify Shannon: Wash STARTED'
- id: '1689645638650'
  alias: Andy iPhone Alert - Home Assistant Successful Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notify_device: d756f8bb367b2b5692b4b3c309ef1e59
- id: '1689731361292'
  alias: Andy iPad Alert - Home Assistant Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notify_device: c13042b5a1081cf01c5158e2590a125e
- id: '1692495737792'
  alias: Andy - Far Away Flag, Turn OFF
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icloud3_v3_zone_distance") | float
      <= 5}}'
  condition:
  - condition: state
    entity_id: sensor.andys_iphone_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
    alias: Confirm Andy ZoneDistance:FromZone is home
    enabled: false
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'on'
  action:
  - alias: 'Andy Far Away Flag: Turn off'
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1692507094295'
  alias: Andy - Far Away Flag, Turn ON
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icloud3_v3_zone_distance") | float
      > 5}}'
  condition:
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'off'
  action:
  - alias: 'Andy Far Away Flag: Turn on'
    service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1692508484995'
  alias: HA - Started Flag, Set
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:20
  - service: input_boolean.turn_on
    entity_id: input_boolean.ha_started_flag
  mode: single
- id: '1692654415536'
  alias: Shannon - Far Away Flag, Turn OFF
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.shannons_iphone14_icloud3_v3_zone_distance
    below: 5
  condition:
  - alias: Confirm Shannon ZoneDistance:FromZone is not home
    condition: state
    entity_id: sensor.shannons_iphone14_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
  action:
  - service: input_boolean.turn_off
    alias: 'Shannon Far Away Flag: Turn off'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1692654492984'
  alias: Shannon - Far Away Flag, Turn ON
  description: ''
  trigger:
  - alias: When Shannon Zone Distance is above 5 mi
    platform: numeric_state
    entity_id:
    - sensor.shannons_iphone14_icloud3_v3_zone_distance
    above: 5
  condition:
  - alias: Confirm Shannon ZoneDistance:FromZone is not home
    condition: state
    entity_id: sensor.shannons_iphone14_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
  action:
  - service: input_boolean.turn_on
    alias: 'Shannon Far Away Flag: Turn on'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1692661845283'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device: 1bad7ecca6027f6be716bd33bbcd5d3d
      only_after: 06:00:00
      only_before: '20:00:00'
      mobile_app_device_2: 1bad7ecca6027f6be716bd33bbcd5d3d
      send_to_ha: false
      reminder_hours: '12'
- id: '1696208711501'
  alias: Time to Feed The Dogs
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.78
    target:
      entity_id: media_player.kitchen_homepod_mini
  - service: tts.cloud_say
    data:
      cache: true
      message: 'Alert! Bueller and Hotchee are hungry. Please, feed them or else they
        will wreck your place. Well, they might do that anyway. You have been warned. '
      entity_id: media_player.kitchen_homepod_mini
  mode: single
- id: '1699678247718'
  alias: Hue play bars off when ATV turn off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.theater_appletv_4k
    to: standby
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - media_player.theater_appletv_4k
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.hue_play_bars
  mode: single
- id: '1699757335263'
  alias: Bathroom Lights Unavailable (Status Off)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_lights
    to: unavailable
  condition: []
  action: []
  mode: single
- id: '1700030435113'
  alias: WakeOnLAN
  description: Turns on Andy's Office computer at home via Wake-On-Lan magic packets
  trigger:
  - platform: state
    entity_id:
    - input_button.wake_on_lan
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      broadcast_port: 9
      mac: b4-2e-99-4b-72-3b
  mode: single
- id: '1701389767678'
  alias: Shannon - Open Garage when Arriving Home
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.shannons_iphone14_icloud3_v3_zone_distance")  |
      float <= 0.20}}'
  - platform: state
    entity_id:
    - sensor.shannons_iphone14_icloud3_v3_zone_name
    to: Home
  condition:
  - condition: state
    entity_id: input_boolean.shannon_driving_flag
    state: 'on'
  - condition: not
    conditions:
    - condition: time
      after: '23:00:00'
      before: 06:00:00
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    alias: Make sure it is not between 11pm - 6am
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garage_door
    data: {}
  - service: notify.mobile_app_shannonsiphone14_iosapp
    data:
      title: Hey Honey
      message: I love you so much! I hope your first day back after the Holidays was
        amazing! Come on in. Bueller is awaiting your arrival. Hachi is already by
        your side because she's crazy fasto burrito
  mode: single
- id: '1701403399257'
  alias: Hue, Friends Of Hue switch, 4 button, all functions
  description: ''
  use_blueprint:
    path: MrBunbao/hue_dimmer_switch.yaml
    input:
      hue-switch-button1:
      - event.hue_dimmer_switch_2_button_1
      hue-switch-button2:
      - event.hue_dimmer_switch_2_button_2
      hue-switch-button3:
      - event.hue_dimmer_switch_2_button_3
      hue-switch-button4:
      - event.hue_dimmer_switch_2_button_4
      button_1_short_release: []
      button_2_short_release: []
      button_4_short_release: []
      button_1_press:
      - service: light.toggle
        target:
          entity_id: light.bedroom_ceiling_fan_lights
        data:
          brightness_pct: 100
      button_4_press:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.bedroom_fairy_lights
      button_2_press:
      - service: light.toggle
        target:
          entity_id: light.bedroom_ceiling_fan_lights
        data: {}
      - service: switch.toggle
        target:
          entity_id: switch.bedroom_fairy_lights
        data: {}
      button_3_press:
      - service: light.turn_on
        target:
          entity_id: light.bedroom_ceiling_fan_lights
        data:
          brightness_step_pct: -25
- id: '1701968903041'
  alias: Andy - Driving Flag Turn ON
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icloud3_v3_zone_distance") | float
      > 2}}'
  condition:
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.andy_driving_flag
  mode: single
- id: '1701969511597'
  alias: Andy - Driving Flag Turn OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.andys_iphone_icloud3_v3
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.andy_driving_flag
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.andy_driving_flag
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1701993016491'
  alias: Shannon - Driving Flag Turn OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.shannons_iphone14_icloud3_v3
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.shannon_driving_flag
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      device_id: []
      area_id: []
      entity_id: input_boolean.shannon_driving_flag
    data: {}
  mode: single
- id: '1701993119197'
  alias: Shannon - Driving Flag Turn ON
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.shannons_iphone14_icloud3_v3_zone_distance")
      | float > 2}}'
  condition:
  - condition: state
    entity_id: input_boolean.shannon_far_away_flag
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.shannon_driving_flag
  mode: single
