- id: '1673393658598'
  alias: Shannon - Open Garage when Arriving Home
  description: Open Garage when Arriving Home
  trigger:
  - platform: state
    entity_id:
    - sensor.shannons_iphone_icloud3_v3_badge
    to: Home
  - platform: state
    entity_id:
    - sensor.shannons_iphone_icloud3_v3_zone_fname
    to: Home
    enabled: false
  - platform: device
    device_id: 080a866185d8aca817cbb2b42c290b23
    domain: device_tracker
    entity_id: d8e6c987505369115832576708a399c3
    type: enters
    zone: zone.home
    alias: Shannon enters home zone
  condition:
  - condition: state
    entity_id: sensor.shannons_iphone_activity
    state: Automotive
  - condition: state
    entity_id: cover.garage_door
    state: closed
  action:
  - service: notify.mobile_app_shannons_iphone
    data:
      title: A message from future Hubby
      message: Welcome to our beloved Home beautiful. <3
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_shannons_iphone
    data:
      title: A message from Hachi and Bueller
      message: WE DIDN'T EAT ANYTHING TODAY :D
  mode: single
- id: '1683608811710'
  alias: Andy - Open Garage when Arriving Home
  description: Open Garage when Arriving Home
  trigger:
  - platform: state
    entity_id:
    - sensor.andys_iphone_icloud3_v3_badge
    to: Home
  - platform: state
    entity_id:
    - sensor.andys_iphone_icloud3_v3_zone_fname
    to: Home
  - platform: device
    device_id: e839b86e91bd70de7fd57892b38bad92
    domain: device_tracker
    entity_id: 3930cf0355f73095f54dcea2e39ff6e1
    type: enters
    zone: zone.home
  - platform: numeric_state
    entity_id: sensor.andys_iphone_icloud3_v3_home_distance
    below: 0.1
  condition:
  - condition: state
    entity_id: sensor.andys_iphone_15_activity
    state: Automotive
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: cover.garage_door
    state: closed
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_andys_iphone_15
    data:
      title: Welcome home Pops
      message: Hope your day was well my guy. Come on in.
  mode: single
- id: '1689609244173'
  alias: Washer Machine - Wash cycle finish
  description: Washer Machine - Wash cycle finish
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.eve_energy_7a9c_power
      starting_hysteresis: 1
      starting_threshold: 5
      finishing_threshold: 15
      actions:
      - service: notify.mobile_app_andys_iphone_15
        data:
          message: Washer has finished. Get it before it stinks, ew!
          title: Washer Machine Cycle Finished
      - service: notify.mobile_app_shannons_iphone
        data:
          title: Washer Machine Cycle Finished
          message: A laundry wash cycle has completed. I suggest you do something
            about that if it's yours,  sooner than later or else you'll be sad.
      pre_actions:
      - service: notify.mobile_app_andys_iphone_15
        data:
          title: Washer machine cycle just started
          message: I'll let you know when it's done, sir.
      - service: notify.mobile_app_shannons_iphone
        data:
          message: A washer machine cycle has started. I will let you know when it
            is finished. Love you.
          title: Hello, Madam,
- id: '1689645638650'
  alias: Andy iPhone Alert - Home Assistant Successful Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notify_device: d756f8bb367b2b5692b4b3c309ef1e59
- id: '1689731361292'
  alias: Andy iPad Alert - Home Assistant Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notify_device: c13042b5a1081cf01c5158e2590a125e
- id: '1692495737792'
  alias: Andy - Far Away Flag, Turn Off
  trigger:
  - platform: numeric_state
    entity_id: sensor.andys_iphone_icloud3_v3_zone_distance
    below: 5
  condition:
  - condition: state
    entity_id: sensor.andys_iphone_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
    alias: Confirm Andy ZoneDistance:FromZone is home
  action:
  - alias: 'Andy Far Away Flag: Turn off'
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1692507094295'
  alias: Andy - Far Away Flag, Turn On
  trigger:
  - platform: numeric_state
    entity_id: sensor.andys_iphone_icloud3_v3_zone_distance
    above: 5
  condition:
  - condition: state
    entity_id: sensor.andys_iphone_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
    alias: Confirm Andy ZoneDistance:FromZone is home
  action:
  - alias: 'Andy Far Away Flag: Turn on'
    service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1692508484995'
  alias: HA - Started Flag, Set
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:20
  - service: input_boolean.turn_on
    entity_id: input_boolean.ha_started_flag
  mode: single
- id: '1692640124048'
  alias: Andy - On Dog Walk - Close Garage
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.andys_iphone_icloud3_v3_zone_name
    to: Away
    from: Home
  condition:
  - condition: state
    entity_id: input_boolean.ha_started_flag
    state: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - condition: numeric_state
    entity_id: sensor.andys_iphone_icloud3_v3_home_distance
    above: 0.1
    enabled: false
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.andys_iphone_bssid_2
      state: 40:9:4a:1:6c:96
    enabled: false
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: script.1692640751447
    data: {}
  mode: single
- id: '1692654415536'
  alias: Shannon - Far Away Flag, Turn Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.shannons_iphone_icloud3_v3_zone_distance
    below: 5
  condition:
  - condition: state
    entity_id: sensor.shannons_iphone_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
    alias: Confirm Shannon ZoneDistance:FromZone is not home
  action:
  - service: input_boolean.turn_off
    alias: 'Shannon Far Away Flag: Turn off'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1692654492984'
  alias: Shannon - Far Away Flag, Turn On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.shannons_iphone_icloud3_v3_zone_distance
    above: 5
    alias: When Shannon Zone Distance is above 5 mi
  condition:
  - condition: state
    entity_id: sensor.shannons_iphone_icloud3_v3_zone_distance
    attribute: from_zone
    state: home
    alias: Confirm Shannon ZoneDistance:FromZone is not home
  action:
  - service: input_boolean.turn_on
    alias: 'Andy Far Away Flag: Turn on'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1692661845283'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device: d756f8bb367b2b5692b4b3c309ef1e59
      only_after: 06:00:00
      only_before: '20:00:00'
      mobile_app_device_2: c13042b5a1081cf01c5158e2590a125e
- id: '1696208711501'
  alias: Time to Feed The Dogs
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: tts.cloud_say
    data:
      cache: true
      message: 'Alert! Bueller and Hachi are hungry. Please, feed them or else they
        will wreck your place. Well, they might do that anyway. You have been warned. '
      entity_id: media_player.kitchen
  mode: single
- id: '1699585606904'
  alias: Cruise Ship Announcement
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen_homepod_mini
    data:
      media_content_id: media-source://media_source/local/Ship Announcement.mp3
      media_content_type: audio/mpeg
    metadata:
      title: Ship Announcement.mp3
      thumbnail:
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://media_source
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen_homepod_mini
      message: "Attention all delightful passengers, this is your Captain speaking.\n\nAs
        we navigate these enchanting waters, I must share a secret as vast as the
        sea itself. There’s someone special among us who has commandeered the ship
        of my heart with her charm and grace.\n\nTo the one who makes every sunset
        more radiant and every horizon a promise of adventure, know that my love for
        you is as endless as the ocean and as timeless as the tides.\n\nWith you,
        every journey is a fairytale. Here’s to our voyage of love, may it be as magical
        and wondrous as the happiest place on earth.\n\nThank you for embarking on
        this journey with me. Now, let's make waves of joy and cruise into a future
        filled with love.\n\nCaptain over and out. ❤️\U0001F6A2"
      cache: true
  mode: single
- id: '1699678247718'
  alias: Hue play bars off when ATV turn off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.theater_appletv
    to: standby
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - media_player.theater_appletv
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.hue_play_bars
  mode: single
- id: '1699757335263'
  alias: Bathroom Lights Unavailable (Status Off)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_lights
    to: unavailable
  condition: []
  action: []
  mode: single
- id: '1700030435113'
  alias: WakeOnLAN
  description: Turns on Andy's Office computer at home via Wake-On-Lan magic packets
  trigger:
  - platform: state
    entity_id:
    - input_button.wake_on_lan
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      broadcast_port: 9
      mac: b4-2e-99-4b-72-3b
  mode: single
